Output demo/functionality/up.mp4
Source demo/common.tape
Source demo/session.tape

Type "iwant up"
Sleep 500ms
Enter
Wait+Screen /What do you want to launch/
Sleep 800ms
Down 2
Sleep 500ms
Enter
Wait+Screen /Where do you want to launch/
Sleep 800ms
Enter
Wait+Screen /On-demand or spot/
Sleep 800ms
Enter
Wait+Screen /Autostop after/
Sleep 800ms
Enter
Wait+Screen /Ready to launch/
Sleep 800ms
Enter
Wait+Screen /Model ready/
Wait+Line /❯$/
Sleep 4s
